const express=require('express')
const router=express.Router()
const {signupAdmin,loginAdmin,verifyAdmin}=require('../controllers/auth')
const {createCategory,addState,addCity}=require('../controllers/category')
const {isAuthenticate,isAdmin}=require('../middleware/middleware')
const {getAllCategory,getCityAndState}=require('../controllers/category')
router.post('/signupadmin',signupAdmin)
router.post('/loginadmin',loginAdmin)
router.post('/createcategory',isAuthenticate,isAdmin,createCategory)
router.post('/addcity',isAuthenticate,isAdmin,addCity)
router.post('/addstate',isAuthenticate,isAdmin,addState)
router.post('/verifyadmin',isAuthenticate,verifyAdmin)
router.get('/getallcategory',isAuthenticate,getAllCategory)
router.get('/city/state',getCityAndState)
module.exports=router